[package]
name = "alive"
version = "0.1.0"
authors = ["David Gage <whytheplatypus@gmail.com>"]

[dependencies]
hyper = "0.10"
hyper-native-tls = "0.2.3"
serde = "1.0.8"
serde_json = "1.0"
serde_derive = "1.0.8"
